---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "axians-netbox-plugin-pdu/netbox:${NETBOX_VER}-py${PYTHON_VER}"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./base_configuration.py:/opt/netbox/netbox/netbox/base_configuration.py
      - ./netbox_${NETBOX_VER}/configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../axians_netbox_pdu:/source/axians_netbox_pdu
    tty: true
  scheduler:
      build:
        context: ../
        dockerfile: development/Dockerfile
      image: "axians-netbox-plugin-pdu/netbox:${NETBOX_VER}-py${PYTHON_VER}"
      command: sh -c "python manage.py pduscheduler"
      depends_on:
        - netbox
      env_file:
        - ./dev.env
      volumes:
        - ./base_configuration.py:/opt/netbox/netbox/netbox/base_configuration.py
        - ./netbox_${NETBOX_VER}/configuration.py:/opt/netbox/netbox/netbox/configuration.py
        - ../axians_netbox_pdu:/source/axians_netbox_pdu
      tty: true
  worker:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "axians-netbox-plugin-pdu/netbox:${NETBOX_VER}-py${PYTHON_VER}"
    command: sh -c "python manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes:
      - ./base_configuration.py:/opt/netbox/netbox/netbox/base_configuration.py
      - ./netbox_${NETBOX_VER}/configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../axians_netbox_pdu:/source/axians_netbox_pdu
    tty: true
  postgres:
    image: postgres:10
    env_file: dev.env
    volumes:
      - pgdata_axians_netbox_pdu:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_axians_netbox_pdu: